### ISSUE TITLE
Waiting for email...

### ISSUE THREAD

**Issue by manofmanytalents** [donnersyt/ModernWarfareWarzoneSkins#1]
Stuck on this. I have tried to open mail.py however it doesn't work and instantly closes as soon as I attempt to open it.

**Comment by donneeers** [comment]
**mail.py** is just an additional library. i'm unsure what your issue is. are you running the **PawnTakesPawn.py** file?

**Comment by manofmanytalents** [comment]
Yeah, sorry about that. I am running the PawnTakesPawn.py and it gets stuck on a 'Waiting for email...' message.

**Comment by donneeers** [comment]
It appears that they've removed this promotion from the site and there is a new one, I'll push an update for the new skin 👍

EDIT:

Pushed an update (albeit, very messy code!) that should now work.
They changed the way that logging to the website works and also replaced the promotion for the warzone skin with a new one.
